version: "3.8"

services:
  # DATABASE
  db:
    image: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lfrrfh333#
      POSTGRES_DB: nestjs-shop
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    command: >
      sh -c "npm install && npm run db:migrate && npm start"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - db
    restart: always

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
      - /client/src/app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: megadrive652@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Lfrrfh333#
    ports:
      - 8080:80

volumes:
  pgdata:
  logs:
